### ISSUE TITLE
Malformed JSON error after 1.0.1 update

### ISSUE THREAD

**Issue by pderksen** [dannyvankooten/edd-helpscout#11]
After the 1.0.1 update I got an "internal server error" message showing up in the sidebar on all my Help Scout tickets. Before that EDD + software licensing was working great linking to both payment records and license keys.

I turned debug mode on in Help Scout, and the error is: "Json Parser: Syntax error, malformed JSON".

I double-checked my line in wp-config.php and it still matches up.
define( 'HELPSCOUT_SECRET_KEY', 'random-40-character-key' );

This is on 2 different sites running the latest of EDD + SL. Cleared the object cache and all that too. They're both running on WP Engine.

This has been a super-helpful plugin, so thanks for the work on it so far!

*I'd happily pay for a supported pro version FYI, if that was ever under consideration. Not sure how many folks are using this plugin but it has become a huge time saver for me and my support folks.* :)

**Comment by pderksen** [comment]
Ok I figured out the issue here.

HelpScout requires an SSL callback URL in any custom app, but I was forcing non-SSL on all but checkout pages on my WP site. In my case, this was set in my host's control panel (WP Engine).

Since EDD-HelpScout was accessing the root URL, it was redirecting an SSL URL to a non-SSL URL and breaking the connection.

To fix this I simply added an exclusion to force non-SSL for an arbitrary URL with my host and matched the HelpScout app's callback URL to this (i.e. https://mysite.com/edd-helpscout).

**Comment by dannyvankooten** [comment]
Great - glad you figured it out @pderksen. 

Don't think HelpScout required SSL before but I think it's great they do now. :) After all, it's customer data that's passed between the two servers.

Thanks for letting me know it's not necessarily something in the plugin code that was causing this!
