### ISSUE TITLE
Multiple EDD Helpscout plugins

### ISSUE THREAD

**Issue by grappler** [dannyvankooten/edd-helpscout#13]
Why are you creating this plugin when there are other similar plugins?

https://github.com/Yoast/helpscout-edd
https://github.com/easydigitaldownloads/EDD-Help-Scout
https://sproutapps.co/help-scout-desk-wordpress-plugin/

**Comment by pippinsplugins** [comment]
The one from Yoast and Easy Digital Downloads are much simpler and not nearly as feature rich. They were done first and this one has largely replaced those.

Sprout Apps was done later.

**Comment by dannyvankooten** [comment]
What Pippin says - this one started off as a fork of the Yoast edd-helpscout repository but then we collaborated on this one. :-)

**Comment by grappler** [comment]
Thanks, sounds good :smile:
