### ISSUE TITLE
Support with Software Licesning

### ISSUE THREAD

**Issue by jameslaws** [dannyvankooten/edd-helpscout#18]
It would be nice if there was support so you could see if the customer licenses were active or expired.

**Comment by pippinsplugins** [comment]
It already supports this.

**Comment by dannyvankooten** [comment]
Yes, it should show the customer's licenses and on which sites they're active (along with a "deactivate" link).

**Comment by jameslaws** [comment]
It shows what sites the license is active on but I don't see where it show if the license is expired.
