### ISSUE TITLE
Fall back to EDD payment lookup by license key

### ISSUE THREAD

**Issue by pderksen** [dannyvankooten/edd-helpscout#19]
I require customers to enter their payment email and license key (generated from EDD Software Licensing) when submitting a support request that goes directly to Help Scout.

However, many enter an unrecognized payment email, probably due to simply forgetting what that email was when they purchased.

It would be nice if this plugin would fall back to looking up their EDD SL license key if in the body of the ticket when the payment can't be found by email.

Thanks!

**Comment by dannyvankooten** [comment]
Hi @pderksen, I looked into this previously but it seems HelpScout does not send the email body. Just the subject. 

You can use the `helpscout_edd_customer_emails` filter for this, it expects an array of emails and all request data is passed into the callback as a parameter. 

This allows you to query your database in any way you like and / override the emails which are used to query the payments.

Hope that helps!

**Comment by pderksen** [comment]
If the license key were in the subject would that help?

Thanks!

**Comment by dannyvankooten** [comment]
Yep, that way you could use the filter as described above. :)

**Comment by dannyvankooten** [comment]
Hey @pderksen,

Heads-up: the name of this filter has changed to `edd_helpscout_customer_emails` for consistency reasons. The change is backwards compatible, the old filter will still work but will eventually be removed.

**Comment by pderksen** [comment]
Great thanks!
