### ISSUE TITLE
Anyone tested this on Pagely?

### ISSUE THREAD

**Issue by adampickering** [dannyvankooten/edd-helpscout#20]
I've added the HELPSCOUT_SECRET_KEY to my wp-config.php file But I keep getting {"html":"Invalid signature"}

https://astoundify.com/edd-hs-api/customer-data.json

It used to work on Digital Ocean, but as soon as I moved to pagely it broke inside of Helpscout showing this message: Invalid signature

any ideas?

**Comment by pippinsplugins** [comment]
I use it on pagely.

You must use https

**Comment by adampickering** [comment]
I'm using HTTPS

**Comment by dannyvankooten** [comment]
Hey @adampickering , I don't see why this wouldn't work on Pagely. Are you 100% sure the `HELPSCOUT_SECRET_KEY` constant is matching with the one in your HelpScout custom app settings?

**Comment by adampickering** [comment]
Got it working! :D :+1: Thanks guys
