### ISSUE TITLE
MultiSite Support

### ISSUE THREAD

**Issue by kmb40** [dannyvankooten/edd-helpscout#21]
Does this work with Multi Site installs? Getting a "Moved Permanently" message where the contents should show.

**Comment by flowdee** [comment]
I've also experienced that on my multisite (subdirectory structure) https://domain.com/en/edd-helpscout-api/customer_info leads into a not found page. 

Any idea how to get it running on a multisite @dannyvankooten ? In case you need help for debugging, just let me know.

**Comment by dannyvankooten** [comment]
Did you use the callback URL from the GitHub README, using the appropriate site URL?

**Comment by dannyvankooten** [comment]
After thinking about this, it could be that there's an issue with the "request listener" logic when working with subdirectory sites. Most likely, it'll work just fine on a subdomain... 

I guess the `includes/class-listener.php` class needs some attention for this to work properly in subdirectories.

**Comment by flowdee** [comment]
It's **not** network-wide activated. And yep double checked the url which is fine and works for the default blog.

Anything you need from me for debugging? Would be great to get this fixed asap 👍 

_When it's not working and your missing it, you really experience how helpful this extension is._

**Comment by dannyvankooten** [comment]
I actually don't expect to have time to look into this anytime soon, so I'd love for someone to pick this up. Too much work these weeks, sorry. 

We're also not using this extension ourself anymore, so I'm guessing it would be best if someone took over this project entirely. 

cc @pippinsplugins

**Comment by kmb40** [comment]
@dannyvankooten What did you start using instead?

**Comment by dannyvankooten** [comment]
@kmb40 We moved away from Easy Digital Downloads and WordPress entirely for our shop platform.

**Comment by pippinsplugins** [comment]
This still works fine for me on multisite (all my sites run multisite).

**Comment by flowdee** [comment]
Pippin, the latest master here from github or the wp.org version?

**Comment by jdevalk** [comment]
@dannyvankooten: We're in the process of moving to WooCommerce so we're not going to pick up this project.

**Comment by dannyvankooten** [comment]
@jdevalk Fair enough, good luck on the migration! In a similar process right now, such fun. :wink:

@pippinsplugins Thanks for letting know! Using subdomains by any chance? I think the use of subdirectories might be the culprit here, @flowdee.

**Comment by flowdee** [comment]
FYI @dannyvankooten for my multisite (subdirectories) i switched back to the wp.org version and indeed this still works fine.

In case @pippinsplugins and his team is not interested in taking over the plugin, I might dig into the code and might think about taking it over if you like.

**Comment by flowdee** [comment]
Yeah the WP.org works fine with multisite sub folders, the current master here unfortunately not.

I prefer you're taking care of it. 👍

**Comment by webzunft** [comment]
@flowdee @pippinsplugins I am actively working on version 2.0, but would need help with this multisite issue, if you still experience it.

**Comment by flowdee** [comment]
Sorry but I'm no longer using Multisite here

**Comment by webzunft** [comment]
Thanks. Will mark this as "help wanted" in case anyone still experiences it and can help with testing something. I am going to move forward with the 2.0 release though.

**Comment by webzunft** [comment]
agreed
