### ISSUE TITLE
Support new Lifetime License in Software Licensing

### ISSUE THREAD

**Issue by cklosowski** [dannyvankooten/edd-helpscout#22]
With an upcoming version of Software licensing, there is the possibility of the `check_license` return containing the string `lifetime` for the `expires value`. 

Throwing a quick PR together to account for this.

**Comment by pippinsplugins** [comment]
@dannyvankooten would love it if this could go out :)

**Comment by dannyvankooten** [comment]
This will get some love this week! :)

**Comment by pippinsplugins** [comment]
Yay!
