### ISSUE TITLE
Way to test with non-SSL callback URLs?

### ISSUE THREAD

**Issue by pderksen** [dannyvankooten/edd-helpscout#27]
Help Scout currently requires custom app callback URLs to be SSL.

Anyone know of any way to test non-SSL callback URLs for changes to this plugin? Trying to run this on a test site.

**Comment by dannyvankooten** [comment]
Hey @pderksen , you can use an `http` URL if you enable "Debug Mode" in the HelpScout App configuration.

**Comment by pderksen** [comment]
Tried that. Still requires an HTTPS url in the app configuration, and only allows you to paste in a non-HTTPS url in a debug popup per request. Kind of a pain, but nothing you can change here I don't think. I may inquire with Help Scout. Thanks!
