### ISSUE TITLE
Recognize EDD 2.6 multiple emails per customer

### ISSUE THREAD

**Issue by pderksen** [dannyvankooten/edd-helpscout#36]
EDD 2.6 (currently in beta) is introducing multiple emails per customer.

https://easydigitaldownloads.com/development/2016/05/26/version-2-6-beta-1-now-available/

I haven't setup a HelpScout "staging" mailbox to test this yet, but does this or will this work? Or is it unknown?

**Comment by pippinsplugins** [comment]
Easy way to support this:

1. Instantiate an instance of `EDD_Customer` using the emails supplied by helpscout
2. Use `get_payments()` method of `EDD_Customer` to grab attached purchases

**Comment by pippinsplugins** [comment]
The `EDD_Customer` class supports instantiation with any attached email.

**Comment by webzunft** [comment]
Fixed in https://github.com/dannyvankooten/edd-helpscout/commit/7094d71d8d08f90ad1a66b6f1528ba3fa26a2075, though not through `EDD_Customer`. I need to find a method that also retrieves payment for an email that is no longer attached to an account.
