### ISSUE TITLE
Resend Purchase Receipt link not working

### ISSUE THREAD

**Issue by pderksen** [dannyvankooten/edd-helpscout#39]
Possibly due to a recent change by HelpScout?

Resend link returns a "-1" in content for me now and doesn't send. Tested a few different customers.

**Comment by pderksen** [comment]
@webzunft No I'm not. Just tested and the re-send receipt icon/link works just fine.

Thanks for asking and it's great to see improvements being worked on!

Let me know if you need me to test out anything else.

**Comment by webzunft** [comment]
Thanks, @pderksen for testing. I would indeed appreciate if you had a look at https://github.com/dannyvankooten/edd-helpscout/issues and let me know which reported issues you are also experiencing or which improvements you would like to see.
