### ISSUE TITLE
"No payments found for Array" when payment email isn't primary one for HS customer.

### ISSUE THREAD

**Issue by pderksen** [dannyvankooten/edd-helpscout#41]
It looks like HS can't tie the customer to the EDD payment when the email for the payment is _not_ the primary one. Using latest on dev branch of this plugin at https://github.com/dannyvankooten/edd-helpscout/commit/0e39e991ceeae62038cbb64f2cc890dc7da51773.

![image](https://cloud.githubusercontent.com/assets/79667/19937472/a63d6b4e-a0de-11e6-902b-757f9bf1add4.png)

For this example, bbb@gmail.com is the email tied to the EDD payment.

Past versions of edd-helpscout used to check secondary or beyond emails of the HS customer to try and tie to the EDD payment if the first email didn't work.

**Comment by dannyvankooten** [comment]
Hi @pderksen,

What's the subject line of the conversation that's causing this error?

**Comment by pderksen** [comment]
Here's a sampling of a few with the error:

WP Simple Pay Support - Change Pay button color, Add "Name" in Stripe Popup
Re: WP Simple Pay Support - How to translate validation error message?
Re: WP Simple Pay Support - Parse Mailchimp tracking to Thank you page

All of them with multiple emails associated with their HS customer profile. It's as if it gives up looking at any email after the first in HS when trying to match the EDD payment.

Thanks!

**Comment by pderksen** [comment]
For now I went back to edd-helpscout 1.1.1, and the old HS app callback URL format, and this is working again.

If I can help out in any way going forward let me know.

**Comment by dannyvankooten** [comment]
Finally ran into this myself @pderksen, should be all good now!

**Comment by pderksen** [comment]
@dannyvankooten Thanks...it works!
