### ISSUE TITLE
Lookup license key info using license key value in Help Scout form

### ISSUE THREAD

**Issue by gspice** [dannyvankooten/edd-helpscout#48]
Often times the email used on a Help Scout support ticket is not attached to the Edd license.  It would be a great feature addition if the license information can be searched and displayed by querying the license key provided in the Help Scout ticket.

**Comment by webzunft** [comment]
@gspice Thank you. Unfortunately, this is not possible, because the Help Scout API does not send the content of the message. So we are not able to work with it.
