### ISSUE TITLE
Check for secondary email addresses

### ISSUE THREAD

**Issue by webzunft** [dannyvankooten/edd-helpscout#50]
Check for purchases also if the user wrote from an email address that is a secondary email in her Customer profile in EDD.

**Comment by drodenbaugh** [comment]
FYI, HelpScout has recently changed their use of secondary emails on profiles.  I had a conversation with their support about this and this extension, specifically.

Basically, it comes down to this:
- They used to allow you to have multiple emails defined on a profile (primary was the first one they used, additional ones could have been added by editing the profile, adding the email (and if the user already exists in HS, say "No Thanks" to the subsequent confirm dialog) to the profile.
- The "No thanks" option no longer adds the email to the profile, so other emails aren't easily added.

I'm pretty sure that multiple emails on a single profile still will check in EDD to find associated purchases (I've been using this for years and it's worked...)

**Comment by webzunft** [comment]
Thanks, that will be helpful!

**Comment by webzunft** [comment]
I updated the description to make it more clear that I was referring to a secondary email address given in the Customer profile in EDD. That does not work.
Since customers are not able to add a secondary address in their profile, this has a lower priority.

**Comment by webzunft** [comment]
fixed with https://github.com/dannyvankooten/edd-helpscout/commit/7094d71d8d08f90ad1a66b6f1528ba3fa26a2075
